### ISSUE TITLE
Embedded dependencies crash on 1.20.1

### ISSUE THREAD

**Issue by FrostedGeulleisia** [Overcontrol1/RandomFishing#5]
Dependencies bundled with the mod (Polymer and Server Translations API) use versions incompatible with 1.20.1, causing a crash (which is hidden unless you extract the dependencies' JARs).
While for Polymer this can be worked around, by simply downloading a compatible version off of Modrinth and editing this mod's json to not reference the invalid version stored within, I was unable to find such a version for the translations API.
The mod seems to work fine without the latter, at least in a singleplayer setting, so it's not _that_ big of a deal, but I hope this gets fixed.

**Comment by Overcontrol1** [comment]
Thanks for letting me know. I appreciate your thorough investigation and troubleshooting. I've uploaded versions on both Modrinth and Github that have the appropriate dependencies and versioning for 1.20.1. This is a band aid fix, but I'm not proficient enough nor do I really have the motivation to set up the proper subprojects to support a high number of Minecraft versions. This means as of right now the mod only supports 1.20.1 and 1.20.4, which to my knowledge are two of the most commonly modded modern Minecraft versions. 

This fix should at the very least stop you from having to download a separate version of Polymer. Please let me know if there are still issues. Have a fine day.
