### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by HockeyZman2000** [Overcontrol1/RandomFishing#6]
Really like the concept of the mod, however there are some endgame items and mods in my pack that I don't want to be obtainable using this. Would it be possible to add configuration for blacklisting single items and/or entire mods from appearing as loot?

**Comment by Overcontrol1** [comment]
I've added this in 1.3. I'll consider adding a tutorial/documentation later, it's a bit late to do right now. There is both mod-wide and individual item blacklisting, both data-driven, so it shouldn't be too hard to edit for your pack. I best get some sleep, so have a good day, and let me know if there's any problems, or if you need help with the files. 👍
